### ISSUE TITLE
Php 8.1.2 compability

### ISSUE THREAD

**Issue by gokhanakdag** [phpro/phpro-mage2-module-logger-handler#3]
- phpro/mage2-module-logger-handler 1.0.4 requires php ^7.0 -> your php version (8.1.2) does not satisfy that requirement.

**Comment by stefliekens** [comment]
Hi @gokhanakdag, you should at least upgrade to [version 4.0.0](https://github.com/phpro/phpro-mage2-module-logger-handler/releases/tag/4.0.0) which has compatibility for PHP 8.1.

**Comment by gokhanakdag** [comment]
Please try to install via composer. It doenst work.

**Comment by stefliekens** [comment]
hi @gokhanakdag , but I can see you are using an old version (1.0.4) of the module. Probably you need to update the version in your composer.json file first.
